# WhatATheme
markdown: kramdown

# URL of the Site
url: ''
# Base URL of the Site (i.e., Name of the Repository in which the Site is hosted)
baseurl: 

# Title of the Site
title: Henry Lambert
# Description of the Site
description: Aerospace Engineering Student at Worcester Polytechnic Institute
# URL of Image of the Site
site-image: /WhatATheme/assets/images/meta.jpg
# Keywords of the Site
site-keywords: Site, Template, Theme
# URL for the Image of custom Favicon
favicon-url: 

# URL of the Image of Custom Hero Image (i.e., the image in the background of the very first section of the Homepage)
heroimage: MJB_2322.JPG

# Social Media and Contact
# If you don't want to use any icon, you can leave them blank.
email: jhlambert@wpi.edu
facebook_username: 
twitter_username: 
instagram_username: henry.lambert03
linkedin_username: henry-lambert-851474173
github_username:  
youtube_channel_id: UC_VxaGwYODitA6YobB5201Q
reddit_username: 
behance_username:
dribbble_username: 
spotify_username:

# Google Analytics
google-analytics: 

# Disqus
disqus-shortname: 

# Name of the Author
author-name: Henry Lambert
# URL for the Image of the Author
author-image: img/henryprofile.jpg
# 60 Words About the Author
author-about: I am an undergraduate student at Worcester Polytechnic Institute (WPI) studying Aerospace Engineering and minoring in Computer Science. I love to tinker and create my own projects as well as work on team projects. While at WPI I have had the chance to gain professional experience as well. Here is all of my work! 
# URL to the Author's Profile (i.e., Github, Twitter, Stackoverflow, etc)
author-url: https://github.com/thedevslot

# SASS
sass:
  sass_dir: _sass
  style: compressed

# Build settings
plugins:
  - jekyll-admin
  - jekyll-feed

# Permalink
permalink: "blog/:title"

# Compress
compress_html:
  clippings: all

# Defaults
defaults:
  -
    scope:
      type: 'posts'
    values:
      layout: post
      post-image: ""
      description: ""
      tags:
        - ""
  -
    scope:
      type: 'pages'
    values:
      layout: page

# Exclude
exclude:
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
